'''Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

'''

list_fibonacci = [1,2]
list_sum = []

aux = 0
aux2 = 0


for n in range(2,1000):

    aux = list_fibonacci[n-1] + list_fibonacci[n-2]
    list_fibonacci.append(aux)
    if aux > 4000000:
        list_fibonacci.remove(aux)
        break

for i in (list_fibonacci):
        
    if (i%2) == 0:
        list_sum.append(i)
        aux2 += i
    
print(aux2)    
#print(list_fibonacci)

